project_id = "dqqfzpghixfvhhpxfgwv"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false

[functions.seed-real-users]
verify_jwt = false

[functions.zoom-get-token]
verify_jwt = false

[functions.zoom-create-meeting]
verify_jwt = false
