// Derives the lightweight catalog index (no courses/colleges) from the full catalog.
// Used by scripts/build-catalog-index.ts to write catalog.generated.ts, and by tests to prove it is current.
import type { University } from "./types";
import { classifyCollege, collegeToCategory } from "./categories";
import { slugify } from "@/lib/slugify";

const MIN_INDEXABLE_COURSES = 5;

export interface UniversitySummary {
  id: string;
  name_ar: string;
  name_en: string;
  website: string;
  type: "public" | "private";
  founded: number;
  country_code: string;
  country_ar: string;
  country_en: string;
  logo?: string;
  colleges: number;
  departments: number;
  courses: number;
  indexable: boolean;
}

export interface SubjectSummary {
  name_en: string;
  name_ar: string;
  slug: string;
  category_ar: string;
  /** Sum of department course counts (what the subjects grid shows). */
  courses: number;
  /** Distinct course codes (used for indexability). */
  uniqueCourses: number;
  countries: string[];
}

export interface CategorySummary {
  key: string;
  departments: number;
}

export interface CatalogIndex {
  universities: UniversitySummary[];
  subjects: SubjectSummary[];
  categories: CategorySummary[];
  totals: { departments: number; courses: number };
}

export function buildCatalogIndex(all: University[]): CatalogIndex {
  const universities: UniversitySummary[] = all.map((u) => {
    const courses = (c: University["colleges"][number]) =>
      c.departments.reduce((s, d) => s + d.courses.length, 0);
    return {
      id: u.id,
      name_ar: u.name_ar,
      name_en: u.name_en,
      website: u.website,
      type: u.type,
      founded: u.founded,
      country_code: u.country_code,
      country_ar: u.country_ar,
      country_en: u.country_en,
      ...(u.logo ? { logo: u.logo } : {}),
      colleges: u.colleges.length,
      departments: u.colleges.reduce((s, c) => s + c.departments.length, 0),
      courses: u.colleges.reduce((s, c) => s + courses(c), 0),
      indexable: u.colleges.some((c) => courses(c) >= MIN_INDEXABLE_COURSES),
    };
  });

  const subjMap = new Map<
    string,
    Omit<SubjectSummary, "slug" | "uniqueCourses"> & { codes: Set<string> }
  >();
  const catMap = new Map<string, number>();
  let departments = 0;
  let totalCourses = 0;
  for (const u of all) {
    for (const c of u.colleges) {
      const catKey = classifyCollege(c.name_en);
      catMap.set(catKey, (catMap.get(catKey) || 0) + c.departments.length);
      for (const d of c.departments) {
        departments++;
        totalCourses += d.courses.length;
        // Unclassified import bucket: kept privately in the data, never a public subject.
        if (d.name_en.trim().toUpperCase() === "PENDING") continue;
        let s = subjMap.get(d.name_en);
        if (!s) {
          s = {
            name_en: d.name_en,
            name_ar: d.name_ar,
            category_ar: collegeToCategory[catKey]?.ar || catKey,
            courses: 0,
            countries: [],
            codes: new Set(),
          };
          subjMap.set(d.name_en, s);
        }
        s.courses += d.courses.length;
        d.courses.forEach((x) => s!.codes.add(x.code || x.name_en));
        if (!s.countries.includes(u.country_code))
          s.countries.push(u.country_code);
      }
    }
  }

  // Slugs: sorted so collision suffixes don't depend on data order.
  const slugByName = new Map<string, string>();
  const used = new Set<string>();
  for (const name of [...subjMap.keys()].sort((a, b) =>
    a.localeCompare(b, "en"),
  )) {
    const base = slugify(name) || "subject";
    let slug = base;
    let n = 2;
    while (used.has(slug)) slug = `${base}-${n++}`;
    used.add(slug);
    slugByName.set(name, slug);
  }

  const subjects: SubjectSummary[] = [...subjMap.values()].map(
    ({ codes, ...s }) => ({
      ...s,
      slug: slugByName.get(s.name_en)!,
      uniqueCourses: codes.size,
    }),
  );

  return {
    universities,
    subjects,
    categories: [...catMap.entries()].map(([key, n]) => ({
      key,
      departments: n,
    })),
    totals: { departments, courses: totalCourses },
  };
}

const HEADER = `// GENERATED by scripts/build-catalog-index.ts from the per-country modules. Do not edit.\n`;

/** Country directory index: university identifiers + counts only (no colleges/courses). */
export const renderUniversityIndexModule = (idx: CatalogIndex) =>
  HEADER +
  `import type { UniversitySummary } from "./buildIndex";\n\n` +
  `export const UNIVERSITY_INDEX: UniversitySummary[] = ${JSON.stringify(idx.universities)};\n`;

/** Subject index: department names, slugs and counts, for subject/category pages and URL slugs. */
export const renderSubjectIndexModule = (idx: CatalogIndex) =>
  HEADER +
  `import type { SubjectSummary, CategorySummary } from "./buildIndex";\n\n` +
  `export const SUBJECT_INDEX: SubjectSummary[] = ${JSON.stringify(idx.subjects)};\n` +
  `export const CATEGORY_INDEX: CategorySummary[] = ${JSON.stringify(idx.categories)};\n` +
  `export const CATALOG_TOTALS = ${JSON.stringify(idx.totals)};\n`;
