// Splits the catalog into one module per university (src/data/universities/unis/<cc>/<id>.ts)
// and rewrites the country files as thin re-exports. Re-runnable; values are copied unchanged.
// Run: bun scripts/split-catalog.ts
import { mkdirSync, writeFileSync } from "node:fs";
import { allUniversities } from "../src/data/universities/all";

const DIR = "src/data/universities";
const byCountry = new Map<string, string[]>();
for (const u of allUniversities) {
  const cc = u.country_code.toLowerCase();
  const file = u.id.toLowerCase();
  mkdirSync(`${DIR}/unis/${cc}`, { recursive: true });
  writeFileSync(
    `${DIR}/unis/${cc}/${file}.ts`,
    `// GENERATED by scripts/split-catalog.ts — one university per module so pages load only what they show.\n` +
      `import type { University } from "../../types";\n\n` +
      `export const university: University = ${JSON.stringify(u)};\n`,
  );
  byCountry.set(cc, [...(byCountry.get(cc) || []), file]);
}
for (const [cc, files] of byCountry) {
  const names = files.map((_, i) => `u${i}`);
  writeFileSync(
    `${DIR}/${cc}.ts`,
    `// ${cc.toUpperCase()} universities, assembled from per-university modules. Scripts/tests only (via ./all);\n` +
      `// UI code loads single universities through ./loader.\n` +
      `import type { University } from "./types";\n` +
      files
        .map((f, i) => `import { university as ${names[i]} } from "./unis/${cc}/${f}";`)
        .join("\n") +
      `\n\nexport const universities: University[] = [${names.join(", ")}];\n`,
  );
}
console.log(`split ${allUniversities.length} universities`);
