/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyTutorRouteImport } from './routes/apply-tutor'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IgcseRouteImport } from './routes/igcse'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ZoomTestRouteImport } from './routes/zoom-test'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesIdRouteImport } from './routes/courses/$id'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard/teacher'
import { Route as LecturesIdRouteImport } from './routes/lectures/$id'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as SubjectsSubjectSlugRouteImport } from './routes/subjects/$subjectSlug'
import { Route as TeacherOnboardingRouteImport } from './routes/teacher/onboarding'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as TeachersIdRouteImport } from './routes/teachers/$id'
import { Route as UniversitiesIndexRouteImport } from './routes/universities/index'
import { Route as UniversitiesCountrySlugIndexRouteImport } from './routes/universities/$countrySlug/index'
import { Route as UniversitiesCountrySlugUniversitySlugIndexRouteImport } from './routes/universities/$countrySlug/$universitySlug/index'
import { Route as UniversitiesCountrySlugCollegesCollegeIdRouteImport } from './routes/universities/$countrySlug/colleges/$collegeId'
import { Route as UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRouteImport } from './routes/universities/$countrySlug/$universitySlug/colleges/$collegeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyTutorRoute = ApplyTutorRouteImport.update({
  id: '/apply-tutor',
  path: '/apply-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IgcseRoute = IgcseRouteImport.update({
  id: '/igcse',
  path: '/igcse',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoomTestRoute = ZoomTestRouteImport.update({
  id: '/zoom-test',
  path: '/zoom-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/dashboard/teacher',
  path: '/dashboard/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesIdRoute = LecturesIdRouteImport.update({
  id: '/lectures/$id',
  path: '/lectures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectSlugRoute = SubjectsSubjectSlugRouteImport.update({
  id: '/subjects/$subjectSlug',
  path: '/subjects/$subjectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherOnboardingRoute = TeacherOnboardingRouteImport.update({
  id: '/teacher/onboarding',
  path: '/teacher/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/teachers/$id',
  path: '/teachers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesCountrySlugIndexRoute =
  UniversitiesCountrySlugIndexRouteImport.update({
    id: '/universities/$countrySlug/',
    path: '/universities/$countrySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversitiesCountrySlugUniversitySlugIndexRoute =
  UniversitiesCountrySlugUniversitySlugIndexRouteImport.update({
    id: '/universities/$countrySlug/$universitySlug/',
    path: '/universities/$countrySlug/$universitySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversitiesCountrySlugCollegesCollegeIdRoute =
  UniversitiesCountrySlugCollegesCollegeIdRouteImport.update({
    id: '/universities/$countrySlug/colleges/$collegeId',
    path: '/universities/$countrySlug/colleges/$collegeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute =
  UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRouteImport.update({
    id: '/universities/$countrySlug/$universitySlug/colleges/$collegeId',
    path: '/universities/$countrySlug/$universitySlug/colleges/$collegeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply-tutor': typeof ApplyTutorRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/igcse': typeof IgcseRoute
  '/languages': typeof LanguagesRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/zoom-test': typeof ZoomTestRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/lectures/$id': typeof LecturesIdRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRoute
  '/teacher/onboarding': typeof TeacherOnboardingRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/universities/$countrySlug/': typeof UniversitiesCountrySlugIndexRoute
  '/universities/$countrySlug/colleges/$collegeId': typeof UniversitiesCountrySlugCollegesCollegeIdRoute
  '/universities/$countrySlug/$universitySlug/': typeof UniversitiesCountrySlugUniversitySlugIndexRoute
  '/universities/$countrySlug/$universitySlug/colleges/$collegeId': typeof UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply-tutor': typeof ApplyTutorRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/igcse': typeof IgcseRoute
  '/languages': typeof LanguagesRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/zoom-test': typeof ZoomTestRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/lectures/$id': typeof LecturesIdRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRoute
  '/teacher/onboarding': typeof TeacherOnboardingRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/universities/$countrySlug': typeof UniversitiesCountrySlugIndexRoute
  '/universities/$countrySlug/colleges/$collegeId': typeof UniversitiesCountrySlugCollegesCollegeIdRoute
  '/universities/$countrySlug/$universitySlug': typeof UniversitiesCountrySlugUniversitySlugIndexRoute
  '/universities/$countrySlug/$universitySlug/colleges/$collegeId': typeof UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply-tutor': typeof ApplyTutorRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/igcse': typeof IgcseRoute
  '/languages': typeof LanguagesRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/zoom-test': typeof ZoomTestRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/lectures/$id': typeof LecturesIdRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRoute
  '/teacher/onboarding': typeof TeacherOnboardingRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/universities/$countrySlug/': typeof UniversitiesCountrySlugIndexRoute
  '/universities/$countrySlug/colleges/$collegeId': typeof UniversitiesCountrySlugCollegesCollegeIdRoute
  '/universities/$countrySlug/$universitySlug/': typeof UniversitiesCountrySlugUniversitySlugIndexRoute
  '/universities/$countrySlug/$universitySlug/colleges/$collegeId': typeof UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply-tutor'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/igcse'
    | '/languages'
    | '/login'
    | '/my-bookings'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/zoom-test'
    | '/api/health'
    | '/auth/callback'
    | '/checkout/return'
    | '/courses/$id'
    | '/dashboard/teacher'
    | '/lectures/$id'
    | '/subjects/$subjectSlug'
    | '/teacher/onboarding'
    | '/teachers/$id'
    | '/checkout/'
    | '/courses/'
    | '/dashboard/'
    | '/subjects/'
    | '/teachers/'
    | '/universities/'
    | '/universities/$countrySlug/'
    | '/universities/$countrySlug/colleges/$collegeId'
    | '/universities/$countrySlug/$universitySlug/'
    | '/universities/$countrySlug/$universitySlug/colleges/$collegeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/apply-tutor'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/igcse'
    | '/languages'
    | '/login'
    | '/my-bookings'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/zoom-test'
    | '/api/health'
    | '/auth/callback'
    | '/checkout/return'
    | '/courses/$id'
    | '/dashboard/teacher'
    | '/lectures/$id'
    | '/subjects/$subjectSlug'
    | '/teacher/onboarding'
    | '/teachers/$id'
    | '/checkout'
    | '/courses'
    | '/dashboard'
    | '/subjects'
    | '/teachers'
    | '/universities'
    | '/universities/$countrySlug'
    | '/universities/$countrySlug/colleges/$collegeId'
    | '/universities/$countrySlug/$universitySlug'
    | '/universities/$countrySlug/$universitySlug/colleges/$collegeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply-tutor'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/igcse'
    | '/languages'
    | '/login'
    | '/my-bookings'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/zoom-test'
    | '/api/health'
    | '/auth/callback'
    | '/checkout/return'
    | '/courses/$id'
    | '/dashboard/teacher'
    | '/lectures/$id'
    | '/subjects/$subjectSlug'
    | '/teacher/onboarding'
    | '/teachers/$id'
    | '/checkout/'
    | '/courses/'
    | '/dashboard/'
    | '/subjects/'
    | '/teachers/'
    | '/universities/'
    | '/universities/$countrySlug/'
    | '/universities/$countrySlug/colleges/$collegeId'
    | '/universities/$countrySlug/$universitySlug/'
    | '/universities/$countrySlug/$universitySlug/colleges/$collegeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApplyTutorRoute: typeof ApplyTutorRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IgcseRoute: typeof IgcseRoute
  LanguagesRoute: typeof LanguagesRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ZoomTestRoute: typeof ZoomTestRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CoursesIdRoute: typeof CoursesIdRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  LecturesIdRoute: typeof LecturesIdRoute
  SubjectsSubjectSlugRoute: typeof SubjectsSubjectSlugRoute
  TeacherOnboardingRoute: typeof TeacherOnboardingRoute
  TeachersIdRoute: typeof TeachersIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  UniversitiesCountrySlugIndexRoute: typeof UniversitiesCountrySlugIndexRoute
  UniversitiesCountrySlugCollegesCollegeIdRoute: typeof UniversitiesCountrySlugCollegesCollegeIdRoute
  UniversitiesCountrySlugUniversitySlugIndexRoute: typeof UniversitiesCountrySlugUniversitySlugIndexRoute
  UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute: typeof UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-tutor': {
      id: '/apply-tutor'
      path: '/apply-tutor'
      fullPath: '/apply-tutor'
      preLoaderRoute: typeof ApplyTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igcse': {
      id: '/igcse'
      path: '/igcse'
      fullPath: '/igcse'
      preLoaderRoute: typeof IgcseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoom-test': {
      id: '/zoom-test'
      path: '/zoom-test'
      fullPath: '/zoom-test'
      preLoaderRoute: typeof ZoomTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures/$id': {
      id: '/lectures/$id'
      path: '/lectures/$id'
      fullPath: '/lectures/$id'
      preLoaderRoute: typeof LecturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectSlug': {
      id: '/subjects/$subjectSlug'
      path: '/subjects/$subjectSlug'
      fullPath: '/subjects/$subjectSlug'
      preLoaderRoute: typeof SubjectsSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/onboarding': {
      id: '/teacher/onboarding'
      path: '/teacher/onboarding'
      fullPath: '/teacher/onboarding'
      preLoaderRoute: typeof TeacherOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/universities'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$countrySlug/': {
      id: '/universities/$countrySlug/'
      path: '/universities/$countrySlug'
      fullPath: '/universities/$countrySlug/'
      preLoaderRoute: typeof UniversitiesCountrySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$countrySlug/$universitySlug/': {
      id: '/universities/$countrySlug/$universitySlug/'
      path: '/universities/$countrySlug/$universitySlug'
      fullPath: '/universities/$countrySlug/$universitySlug/'
      preLoaderRoute: typeof UniversitiesCountrySlugUniversitySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$countrySlug/colleges/$collegeId': {
      id: '/universities/$countrySlug/colleges/$collegeId'
      path: '/universities/$countrySlug/colleges/$collegeId'
      fullPath: '/universities/$countrySlug/colleges/$collegeId'
      preLoaderRoute: typeof UniversitiesCountrySlugCollegesCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$countrySlug/$universitySlug/colleges/$collegeId': {
      id: '/universities/$countrySlug/$universitySlug/colleges/$collegeId'
      path: '/universities/$countrySlug/$universitySlug/colleges/$collegeId'
      fullPath: '/universities/$countrySlug/$universitySlug/colleges/$collegeId'
      preLoaderRoute: typeof UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApplyTutorRoute: ApplyTutorRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IgcseRoute: IgcseRoute,
  LanguagesRoute: LanguagesRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ZoomTestRoute: ZoomTestRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CoursesIdRoute: CoursesIdRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  LecturesIdRoute: LecturesIdRoute,
  SubjectsSubjectSlugRoute: SubjectsSubjectSlugRoute,
  TeacherOnboardingRoute: TeacherOnboardingRoute,
  TeachersIdRoute: TeachersIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  UniversitiesCountrySlugIndexRoute: UniversitiesCountrySlugIndexRoute,
  UniversitiesCountrySlugCollegesCollegeIdRoute:
    UniversitiesCountrySlugCollegesCollegeIdRoute,
  UniversitiesCountrySlugUniversitySlugIndexRoute:
    UniversitiesCountrySlugUniversitySlugIndexRoute,
  UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute:
    UniversitiesCountrySlugUniversitySlugCollegesCollegeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
